parameters:
- name: string_parameter
  type: string
  default: 'Default string parameter value'
- name: number_parameter
  type: number
  default: 1
- name: boolean_parameter
  type: boolean
  default: true
- name: object_parameter
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
    nested:
      one: apple
      two: pear
      count: 3
- name: step_parameter
  type: step
  default:
    script: echo Default step from step_parameter
    displayName: Run step from step parameter
- name: stepList_parameter
  type: stepList
  default:
    - script: echo Default step one from stepList_parameter
      displayName: Run step from stepList parameter first
    - script: echo Default step two from stepList_parameter
      displayName: Run step from stepList parameter second
- name: job_parameter
  type: job
  default:
    job: job_parameter
    dependsOn: stepList_parameter
    steps:
    - script: echo Default step from job_parameter
      displayName: Run step from job parameter
- name: jobList_parameter
  type: jobList
  default:
    - job: jobList_parameter_one
      dependsOn: job_parameter
      steps:
      - script: echo Default step from jobList_parameter one
        displayName: Run step from jobList parameter one
    - job: jobList_parameter_two
      dependsOn: jobList_parameter_one
      steps:
      - script: echo Default step from jobList_parameter two
        displayName: Run step from jobList parameter two
- name: deploymentJob_parameter
  type: deployment
  default:
    deployment: deploymentJob_parameter
    dependsOn: jobList_parameter_two
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Default step from deploymentJob_parameter
            displayName: Run step from deployment job parameter
- name: deploymentJobList_parameter
  type: deploymentList
  default:
    - deployment: deploymentJobList_parameter_one
      dependsOn: deploymentJob_parameter
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Default step from deploymentJobList_parameter one
              displayName: Run step from deployment job list parameter one
    - deployment: deploymentJobList_parameter_two
      dependsOn: deploymentJobList_parameter_one
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Default step from deploymentJobList_parameter two
              displayName: Run step from deployment job list parameter two
- name: stage_parameter
  type: stage
  default:
    stage: stage_parameter  # name of the stage (A-Z, a-z, 0-9, and underscore)
    dependsOn: first_stage
    jobs:
    - job: stage_parameter_job
      steps:
      - script: echo Default step from stage_parameter
        displayName: Run step from stage parameter
- name: stageList_parameter
  type: stageList
  default:
    - stage: stageList_parameter_one
      dependsOn: stage_parameter
      jobs:
      - job: stageList_parameter_one_job
        steps:
        - script: echo Default step from stageList_parameter_one
          displayName: Run step from stage list parameter one
    - stage: stageList_parameter_two
      dependsOn: stageList_parameter_one
      jobs:
      - job: stageList_parameter_two_job
        steps:
        - script: echo Default step from stageList_parameter_two
          displayName: Run step from stage list parameter two
trigger: none

stages:
- stage: first_stage
  jobs:
  - job: list_simple_parameters
    steps:
    - bash: |
        echo String parameter: ${{ parameters.string_parameter }}
      displayName: Echo string parameter

    - bash: |
        echo Number parameter: ${{ parameters.number_parameter }}
      displayName: Echo number parameter

    - bash: |
        echo Boolean parameter: ${{ parameters.boolean_parameter }}
      displayName: Echo boolean parameter

  - job: list_object_parameters
    dependsOn: list_simple_parameters
    steps:
    - bash: |
        echo Object parameter foo: ${{ parameters.object_parameter.foo }}
        echo Object parameter bar: ${{ parameters.object_parameter.bar }}
      displayName: Echo simple params from object paramater
    
    - ${{ each thing in parameters.object_parameter.things }}:
      - bash: |
          echo Object parameter things: ${{ thing }}
        displayName: Echo param from object list => ${{ thing }}

    - bash: |
        echo Object parameter nested one: ${{ parameters.object_parameter.nested.one }}
      displayName: Echo nested parameter one from object

    - bash: |
        echo Object parameter nested two: ${{ parameters.object_parameter.nested.two }}
      displayName: Echo nested parameter two from object

    - bash: |
        echo Object parameter nested count: ${{ parameters.object_parameter.nested.count }}
      displayName: Echo nested parameter count from object
      
  - job: step_parameter
    dependsOn: list_object_parameters
    steps:
    - ${{ parameters.step_parameter }}

  - job: stepList_parameter
    dependsOn: step_parameter
    steps: ${{ parameters.stepList_parameter }}

  - ${{ parameters.job_parameter }}

  - ${{ parameters.jobList_parameter }}

  - ${{ parameters.deploymentJob_parameter }}

  - ${{ parameters.deploymentJobList_parameter }}

- ${{ parameters.stage_parameter }}

- ${{ parameters.stageList_parameter }}