parameters:
- name: pipelineNameToInvoke
  displayName: Pipeline name to invoke
  type: string
  default: pipeline-with-all-param-types

variables:
- group: pat-vq

trigger: none

jobs:
- template: ../templates/jobs/run-pipeline.yml
  parameters:
    pipelineName: ${{ parameters.pipelineNameToInvoke }}
