parameters:
- name: pipelineName
  type: string

variables:
- group: pat-vq

jobs:
- job: run_pipeline
  displayName: 'Run pipeline: "${{ parameters.pipelineName }}"'

  steps:
  - checkout: self

  - bash: echo $(pat) | az devops login
    displayName: Login to devops
  
  - template: ../steps/get-pipeline-id-by-name.yml
    parameters:
      pipelineName: ${{ parameters.pipelineName }}
      loggedInToDevops: true
  
  - bash: echo $(pipelineId)

  - template: ../steps/invoke-pipeline.yml
    parameters:
      pipelineId: $(pipelineId)
      loggedInToDevops: true
