parameters:
- name: pipelineName
  type: string

jobs:
- job: run_pipeline
  displayName: 'Run pipeline: "${{ parameters.pipelineName }}"'

  steps:
  - checkout: self

  - bash: echo $(System.AccessToken) | az devops login
    displayName: Login to devops
  
  - template: ../steps/get-pipeline-id-by-name.yml
    parameters:
      pipelineName: ${{ parameters.pipelineName }}
      loggedInToDevops: true

  - template: ../steps/invoke-pipeline.yml
    parameters:
      pipelineId: $()