parameters:
- name: pipelineName
  type: string

jobs:
- job: run_pipeline
  displayName: 'Run pipeline: "${{ parameters.pipelineName }}"'

  steps:
  - checkout: self

  - bash: echo $(System.AccessToken) | az devops login
    displayName: Login to devops

  - bash: |
      echo pipelineName: ${{ parameters.pipelineName }} 
    displayName: echo pipelineName
  
  - template: ../steps/get-pipeline-id-by-name.yml
    parameters:
      pipelineName: ${{ parameters.pipelineName }}
      loggedInToDevops: true

  - bash: |
      echo pipelineId: $(pipelineId)